### ISSUE TITLE
Rubbish values from `Node.source` after editing tree

### ISSUE THREAD

**Issue by xcb-xwii** [euclidianAce/ltreesitter#25]
After editing a certain range of the tree using `Tree.edit` / `Tree.edit_s`, some calls to `Node.source` will return rubbish values.

This seems to only apply to nodes that were not affected by the edit. Nodes that did experience changes will return their source text correctly, while unaffected nodes return what I can only assume is junk.

**Comment by euclidianAce** [comment]
Fixed via 9660f206

**Comment by Hibou57** [comment]
I don’t know if it’s related. I noticed Node.type and Node.name are always the same, while the output of print(tree) distinguish field name and type.

Edit: I found no equivalent of Node.source is the C API, so it is an addition of this binding. I wonder how it is implemented. It requires to keep a reference to the source, but the source may not always be a string, it may come from a reader part by part. The `Node.source` property is mimicked in C in the source given there: https://github.com/euclidianAce/ltreesitter/issues/41
