### ISSUE TITLE
install failed in windows

### ISSUE THREAD

**Issue by pkxpp** [euclidianAce/ltreesitter#28]
C:\Users\pkxpp>luarocks install ltreesitter --verbose
Installing http://www.luarocks.org/repositories/rocks/ltreesitter-0.0.7-1.src.rock...
Using http://www.luarocks.org/repositories/rocks/ltreesitter-0.0.7-1.src.rock... switching to 'build' mode

Error: C:\Users\pkxpp\AppData\Local\Temp\luarocks_ltreesitter-0.0.7-1-5034/ltreesitter-0.0.7-1.rockspec: Unknown field issues_url

**Comment by euclidianAce** [comment]
What version of luarocks are you using? If `issues_url` is tripping it up it's probably an older than 3.0. (Though ideally it wouldn't fail to build)
