### ISSUE TITLE
Bundling the tree-sitter lib with ltreesitter

### ISSUE THREAD

**Issue by FourierTransformer** [euclidianAce/ltreesitter#29]
Right now the tree-sitter library is a separate install. I understand the notion of being able to update either library independently (and how it reduces your maintenance burden), but was wondering for ease of install purposes if it was worth combining the two.

I think it could be setup as a git submodule, similar to what the official [python](https://github.com/tree-sitter/py-tree-sitter/tree/master/tree_sitter), [kotlin](https://github.com/tree-sitter/go-tree-sitter), and [go](https://github.com/tree-sitter/go-tree-sitter) bindings do and then combined during the rockspec build process.

As a [maybe temporary?] workaround, I made [ltreesitter-ts](https://github.com/FourierTransformer/ltreesitter-ts) which treats both as a submodules and combines them in the build process.  TBH, I'm not the most proficient at handling Lua bindings, so my setup may not be ideal, but it does _appear to work_ for my use cases.

If you're interested, I could put in a PR that adds the tree-sitter library directly in this repo as a submodule and adds it to the build process.

**Comment by euclidianAce** [comment]
That sounds like a fantastic idea. Anything that can make the installation smoother is a :+1: from me.

The submodule route is probably the way to go and I'd gladly accept a PR for this.
