### ISSUE TITLE
Use in Neovim

### ISSUE THREAD

**Issue by tjdevries** [euclidianAce/ltreesitter#3]
Yo @vigoux should we try and pursue something like this for internal use of treesitter? :) I don't know how any of that works, figured I'd just mention it here.

**Comment by euclidianAce** [comment]
iirc, neovim's internal tree-sitter bindings look kinda similar to these already\*, additionally it uses libUV to open grammars' .so and .dll files whereas I have some ifdefs around `LoadLibrary` and `dlopen`, but as it's open source, neovim is free to steal/use any of this if any of those super cool core-dev people find it neat ;)

\* the only real difference from the glances I've taken are that neovim uses some 5.1-isms (setfenv mostly) to keep references alive, whereas I try to keep this 5.1-5.4 compatible by using the registry and some weak tables

**Comment by vigoux** [comment]
Interesting work!
I'll look into using this for the tree-sitter integration!

Externalising things is always a good thing.
