### ISSUE TITLE
Unable to load parser for c help

### ISSUE THREAD

**Issue by morphykuffour** [euclidianAce/ltreesitter#5]
Hello I wanted to experiment with lua's bindings for treesitter but the demo in the readme does not work. I don't know where to find or generate the **C shared object file**. Any help would be appreciated. Please see attached screenshoot.

![image](https://user-images.githubusercontent.com/23323356/147878914-7fffd439-891d-4f3a-abfa-4354f2540bc0.png)

**Comment by euclidianAce** [comment]
Tree sitter grammars are separate libraries that will need to be installed independently.

The c parser can be [found here](https://github.com/tree-sitter/tree-sitter-c) and will need to be built and installed with the [tree sitter cli](https://github.com/tree-sitter/tree-sitter/blob/master/cli/README.md).

ltreesitter will then look in those paths listed in the error (although it looks like the error message is missing a space)

If you install it and have further issues feel free to report them here!
