### ISSUE TITLE
attempt to index a userdata value on subsequent calls to require

### ISSUE THREAD

**Issue by TorchedSammy** [euclidianAce/ltreesitter#9]
i noticed while trying to add treesitter support to lite xl, any calls after the 1st to `ltreesitter.require` causes an `attempt to index a userdata value` error. it seems that on the call after 1st it returns a plain userdata value (somehow) instead of an ltreesitter parser as testing in lua repl shows:

![](https://safe.kashima.moe/f14cdq5v08qy.png)

**Comment by euclidianAce** [comment]
I've fixed this on my end with the above commit. Thanks for reporting and let me know if the issue persists!

**Comment by takase1121** [comment]
According to @TorchedSammy  it still happens.

**Comment by TorchedSammy** [comment]
(in lite-xl; seems to be fixed with the same testing in lua repl)
